### ISSUE TITLE
No sh file included

### ISSUE THREAD

**Issue by AhmettCelik1** [GAfieldCN/automatic-camera-pointcloud-calibration#2]
There is no sh file which should be executed in this orders 

# install Livox_SDK
git clone https://github.com/Livox-SDK/Livox-SDK.git
cd Livox-SDK
sudo ./third_party/apr/apr_build.sh
cd build && cmake ..
make
sudo make install

**Comment by Garfield-cn** [comment]
Please follow the build instructions in readme of Livox-SDK.
